name: Full CI/CD to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

env:
  AWS_REGION: ap-south-1
  ECR_REPO: 637423217175.dkr.ecr.ap-south-1.amazonaws.com/my-web-app
  DYNATRACE_NAMESPACE: dynatrace

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # -----------------------------
    # Install Terraform
    # -----------------------------
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    # -----------------------------
    # Install Helm
    # -----------------------------
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    # -----------------------------
    # Configure AWS credentials
    # -----------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # -----------------------------
    # Terraform apply
    # -----------------------------
    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve

    # -----------------------------
    # Build Docker image
    # -----------------------------
    - name: Build Docker image
      run: docker build -t my-web-app:latest .

    # -----------------------------
    # Login to ECR
    # -----------------------------
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

    # -----------------------------
    # Tag and Push Docker image
    # -----------------------------
    - name: Tag and Push Docker image
      run: |
        docker tag my-web-app:latest ${{ env.ECR_REPO }}:latest
        docker push ${{ env.ECR_REPO }}:latest

    # -----------------------------
    # Configure kubeconfig for EKS
    # -----------------------------
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig \
          --name ankit-eks-cluster \
          --region ${{ env.AWS_REGION }}

    - name: Verify cluster access
      run: kubectl get nodes

    # -----------------------------
    # Install Dynatrace Operator
    # -----------------------------
    - name: Create Dynatrace namespace
      run: kubectl create namespace ${{ env.DYNATRACE_NAMESPACE }} || true

    - name: Deploy Dynatrace Operator
      run: |
        kubectl apply -f https://github.com/Dynatrace/dynatrace-operator/releases/latest/download/kubernetes.yaml
        echo "Skipping rollout wait — pods may be Pending due to networking/IP limitations"
        sleep 60  # optional buffer for pods to start scheduling

    # -----------------------------
    # Deploy Dynakube with OneAgent token
    # -----------------------------
    - name: Deploy Dynakube
      env:
        ONEAGENT_TOKEN: ${{ secrets.ONEAGENT_TOKEN }}
      run: |
        sed -i "s|<ONEAGENT_PASS_TOKEN>|$ONEAGENT_TOKEN|g" k8s/dynatrace/dynakube.yaml
        kubectl apply -f k8s/dynatrace/dynakube.yaml -n ${{ env.DYNATRACE_NAMESPACE }}
    # -----------------------------
    # Wait for OneAgent pods to be Running
    # -----------------------------
    - name: Wait for Dynatrace OneAgent pods
      run: |
        echo "Waiting for OneAgent pods to be Running..."
        for i in {1..30}; do
          PODS_READY=$(kubectl get pods -n ${{ env.DYNATRACE_NAMESPACE }} \
            -l app.kubernetes.io/component=oneagent -o jsonpath='{.items[*].status.phase}' | grep -c Running || true)
          PODS_TOTAL=$(kubectl get pods -n ${{ env.DYNATRACE_NAMESPACE }} \
            -l app.kubernetes.io/component=oneagent --no-headers | wc -l)
          if [ "$PODS_READY" -eq "$PODS_TOTAL" ] && [ "$PODS_TOTAL" -gt 0 ]; then
            echo "All OneAgent pods are Running!"
            exit 0
          fi
          echo "Waiting... ($i/30)"
          sleep 20
        done
        echo "Timed out waiting for OneAgent pods"
        kubectl get pods -n ${{ env.DYNATRACE_NAMESPACE }}
        exit 1

    # -----------------------------
    # Helm deploy your app
    # -----------------------------
    - name: Helm Upgrade / Install
      working-directory: ./my-sample-app
      run: |
        helm upgrade --install my-web-app . \
          --set image.repository=${{ env.ECR_REPO }} \
          --set image.tag=latest
