name: Full CI/CD to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPO: 637423217175.dkr.ecr.ap-south-1.amazonaws.com/my-web-app
  DYNATRACE_NAMESPACE: dynatrace

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # -----------------------------
    # Install Terraform
    # -----------------------------
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    # -----------------------------
    # Install Helm
    # -----------------------------
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    # -----------------------------
    # Configure AWS credentials
    # -----------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # -----------------------------
    # Terraform apply
    # -----------------------------
    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve

    # -----------------------------
    # Build Docker image
    # -----------------------------
    - name: Build Docker image
      run: docker build -t my-web-app:latest .

    # -----------------------------
    # Login to ECR
    # -----------------------------
    - name:
name: Full CI/CD to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPO: 637423217175.dkr.ecr.ap-south-1.amazonaws.com/my-web-app
  DYNATRACE_NAMESPACE: dynatrace

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # -----------------------------
    # Install Terraform
    # -----------------------------
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    # -----------------------------
    # Install Helm
    # -----------------------------
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    # -----------------------------
    # Configure AWS credentials
    # -----------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # -----------------------------
    # Terraform apply
    # -----------------------------
    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve

    # -----------------------------
    # Build Docker image
    # -----------------------------
    - name: Build Docker image
      run: docker build -t my-web-app:latest .

    # -----------------------------
    # Login to ECR
    # -----------------------------
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ env.ECR_REPO }}

    # -----------------------------
    # Tag and Push Docker image
    # -----------------------------
    - name: Tag and Push Docker image
      run: |
        docker tag my-web-app:latest ${{ env.ECR_REPO }}:latest
        docker push ${{ env.ECR_REPO }}:latest

    # -----------------------------
    # Configure kubeconfig for EKS
    # -----------------------------
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig \
          --name ankit-eks-cluster \
          --region ${{ env.AWS_REGION }}

    - name: Verify cluster access
      run: kubectl get nodes

    # -----------------------------
    # Install Dynatrace Operator & OneAgent via Helm
    # -----------------------------
    - name: Install Dynatrace Operator & OneAgent
      env:
        ONEAGENT_TOKEN: ${{ secrets.ONEAGENT_TOKEN }}
      run: |
        # Create Dynatrace namespace
        kubectl create namespace ${{ env.DYNATRACE_NAMESPACE }} || true

        # Download Dynatrace Operator Helm chart
        curl -LO https://github.com/Dynatrace/helm-charts/releases/latest/download/dynatrace-operator-1.7.1.tgz

        # Install/Upgrade Operator & OneAgent
        helm upgrade --install dynatrace-operator ./dynatrace-operator-1.7.1.tgz \
          --namespace ${{ env.DYNATRACE_NAMESPACE }} --create-namespace \
          --set oneAgent.apiToken=$ONEAGENT_TOKEN \
          --set apiUrl=https://avk11727.live.dynatrace.com/api \
          --set oneAgent.cloudNativeFullStack=true \
          --set activeGate.capabilities={routing,kubernetes-monitoring,metrics-ingest}

    # -----------------------------
    # Wait for OneAgent pods to be Running
    # -----------------------------
    - name: Wait for Dynatrace OneAgent pods
      run: |
        kubectl wait --for=condition=Ready pods \
          -l app.kubernetes.io/component=oneagent \
          -n ${{ env.DYNATRACE_NAMESPACE }} \
          --timeout=600s

    # -----------------------------
    # Helm deploy your app
    # -----------------------------
    - name: Helm Upgrade / Install
      working-directory: ./my-sample-app
      run: |
        helm upgrade --install my-web-app . \
          --set image.repository=${{ env.ECR_REPO }} \
          --set image.tag=latest